@php($publication = $publication ?? null)
<div class="grid gap-6 md:grid-cols-2">
    <div class="md:col-span-2"><label for="title" class="mb-1.5 block text-sm font-semibold text-gray-800">Title <span class="text-red-600">*</span></label><input id="title" name="title" type="text" required maxlength="255" value="{{ old('title', $publication?->title) }}" placeholder="Publication title" class="w-full rounded-lg border-gray-300 px-3 py-2 text-gray-950 focus:border-[#0a5554] focus:ring-[#0a5554]">@error('title')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div class="md:col-span-2"><label for="excerpt" class="mb-1.5 block text-sm font-semibold text-gray-800">Summary</label><textarea id="excerpt" name="excerpt" rows="4" maxlength="2000" placeholder="A short description shown on the public publications page." class="w-full rounded-lg border-gray-300 px-3 py-2 text-gray-950 focus:border-[#0a5554] focus:ring-[#0a5554]">{{ old('excerpt', $publication?->excerpt) }}</textarea>@error('excerpt')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="category" class="mb-1.5 block text-sm font-semibold text-gray-800">Category <span class="text-red-600">*</span></label><input id="category" name="category" type="text" required maxlength="100" list="publication-category-options" value="{{ old('category', $publication?->category ?? 'Research') }}" placeholder="Research" class="w-full rounded-lg border-gray-300 px-3 py-2 text-gray-950 focus:border-[#0a5554] focus:ring-[#0a5554]"><datalist id="publication-category-options"><option value="Research"><option value="Market report"><option value="Founder guide"><option value="Investment education"><option value="Annual report"></datalist>@error('category')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div><label for="published_at" class="mb-1.5 block text-sm font-semibold text-gray-800">Publication date</label><input id="published_at" name="published_at" type="datetime-local" value="{{ old('published_at', $publication?->published_at?->format('Y-m-d\\TH:i')) }}" class="w-full rounded-lg border-gray-300 px-3 py-2 text-gray-950 focus:border-[#0a5554] focus:ring-[#0a5554]"><p class="mt-1 text-xs text-gray-500">If blank when publishing, the current time is used.</p>@error('published_at')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <div class="md:col-span-2"><label for="pdf" class="mb-1.5 block text-sm font-semibold text-gray-800">PDF file <span class="text-red-600">*</span></label>@if($publication?->pdf_original_name)<p class="mb-2 text-sm text-gray-600">Current file: <span class="font-semibold">{{ $publication->pdf_original_name }}</span></p>@endif<input id="pdf" name="pdf" type="file" accept="application/pdf,.pdf" @required(!$publication) class="block w-full rounded-lg border border-gray-300 px-3 py-2 text-sm text-gray-600 file:mr-4 file:rounded-lg file:border-0 file:bg-green-50 file:px-4 file:py-2 file:font-semibold file:text-[#0a5554]"><p class="mt-1 text-xs text-gray-500">PDF only, maximum 20 MB. Uploading a new file replaces the current PDF.</p>@error('pdf')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</div>
    <fieldset class="md:col-span-2"><legend class="mb-2 block text-sm font-semibold text-gray-800">Visibility <span class="text-red-600">*</span></legend><div class="grid gap-3 sm:grid-cols-2"><label class="flex cursor-pointer gap-3 rounded-xl border border-gray-200 p-4 hover:border-green-400"><input type="radio" name="status" value="published" class="mt-1 text-green-600 focus:ring-green-600" @checked(old('status', $publication?->status ?? 'archived') === 'published')><span><strong class="block text-gray-950">Published</strong><small class="text-gray-600">Visible on the public publications page.</small></span></label><label class="flex cursor-pointer gap-3 rounded-xl border border-gray-200 p-4 hover:border-amber-400"><input type="radio" name="status" value="archived" class="mt-1 text-amber-600 focus:ring-amber-600" @checked(old('status', $publication?->status ?? 'archived') === 'archived')><span><strong class="block text-gray-950">Archived</strong><small class="text-gray-600">Saved in admin, hidden from the public.</small></span></label></div>@error('status')<p class="mt-1 text-sm text-red-600">{{ $message }}</p>@enderror</fieldset>
</div>
